In [5]:
import pandas as pd

In [6]:
df = pd.DataFrame({
    'a': [1, 2, 3],
    'b': [4, 5, 6],
    'c': [7, 8, 9],
},
    index=[0, 1, 2])

In [7]:
df

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [17]:
df.loc[0,'a':'b']

a    1
b    4
Name: 0, dtype: int64

In [24]:
df.iloc[0,0]

np.int64(1)

In [25]:
df.iloc[0,0]=5

In [26]:
df

   a  b  c
0  5  4  7
1  2  5  8
2  3  6  9

In [31]:
df.iloc[0, 0]

np.int64(5)

In [32]:
df

   a  b  c
0  5  4  7
1  2  5  8
2  3  6  9

In [33]:
df.sum()

a    10
b    15
c    24
dtype: int64

In [34]:
df.min()

a    2
b    4
c    7
dtype: int64

In [35]:
df.max()

a    5
b    6
c    9
dtype: int64